Switch from period_range to date_range
Before this change test_period_object_column fails with the message
below:

    FAILED qgrid/tests/test_grid.py::test_period_object_column - OverflowError: Maximum recursion level reached

After this change the test passes.

See also
https://github.com/pandas-dev/pandas/issues/53446